Added a new scenario for Container Apps inside of a VNET
Azure-Samples/virtual-network-integration-recipes pull request #44
Opened 2024-10-26 23:18 UTC by aminespinoza10

# Purpose

* This PR updates the scenario uploading a sample of how to deploy a container app inside of a VNET and make it accessible using API Management and App Gateway.
* The sample includes scenarios for Bicep and Terraform including for both of them a bash script that could help to deploy everything in one single step.
* Weather API project has been upgraded from .NET 6 to .NET 8 using the new project template structure (minimal api) but doing the same functionality.

## Does this introduce a breaking change?

``` markdown
[ ] Yes
[X] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

``` markdown
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* In the folder **src/az-containerapps-apim-appgw** there is a README that can work as guidance for any scenario.

* Test the code

``` text
```

## What to Check

Verify that the following are valid

* ...

## Other Information

2024-11-08 21:07 UTC, mluker requested changes
General comments:
- There are references to netcore3.1 in throughout the docs which should be changed to net8.0 due to the upgrade.
- the dev container does not have the appropriate software installed. I had to add the dev container feature `docker-outside-of-docker` and update the dockerfile to install dotnet sdk `RUN sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0`
- I was not able to complete the Bicep run through as there is a missing secret therefore the AppGateway does not get deployed.
- I did a quick scan of the Terraform and added some comments and once the current issues are cleaned up I will do a full Terraform run through.

2024-11-08 21:07 UTC, mluker commented on src/az-containerapps-apim-appgw/README.md
> +bash bicep-deploy.sh
- The path to `bicep-deploy-sh` should be specified or have earlier instructions to `cd` into `src/az-containerapps-apim-appgw/deploy/` and execute `bash/bicep-deploy.sh`
- The permissions on the scripts need have execute `chmod +x`
- There should be instructions to destroy the environment when done (a clean up script or commands)

2024-11-08 21:07 UTC, mluker commented on src/az-containerapps-apim-appgw/deploy/bash/bicep-deploy.sh
> +#!/bin/bash
-If anything in here fails, it should abort running future steps. If certs fail, there is no need to try the bicep deploy as it will fail.
- This script assumes I am in the `src/az-containerapps-apim-appgw/deploy/bicep` folder as it does a `cd ..` command and then tries to run `../bicep/pre/main.bicep`. I should be able to run this script from anywhere and paths within the script should be relative to the scripts running directory.
- If cert creation fails the script should not continue and if the certs already exist it should use them or prompt/overwrite them.
- Resources should probably use random names as there are name collisions happening, especially if the execution fails and re-run it attempted.
- The error occurs {"code": "KeyVaultParameterReferenceSecretRetrieveFailed", "message": "The secret of KeyVault parameter 'wildcardCertificateBase64' cannot be retrieved. Http status code: 'NotFound'. Error message: 'A secret with (name/id) vnet-internal-cert was not found in this key vault. If you recently deleted this secret you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182'. Please see https://aka.ms/arm-keyvault for usage details."}
- warning is output "/workspaces/virtual-network-integration-recipes/src/az-containerapps-apim-appgw/deploy/bicep/app/main.bicep(58,18) : Warning BCP036: The property "cpu" expected a value of type "int | null" but the provided value is of type "'0.25'". If this is a resource type definition inaccuracy, report it using https://aka.ms/bicep-type-issues. [https://aka.ms/bicep/core-diagnostics#BCP036]"

2024-11-08 21:07 UTC, mluker commented on src/az-containerapps-apim-appgw/deploy/bash/bicep-deploy.sh
> +az keyvault certificate import --vault-name test-internal-001-kv --name root-cert --file root-cert.pfx --password "s5p2rm1n"
* These cert paths are not correct. The Certs live in the certs folder.
* Running user and/or MI cannot import the cert as they are missing those permissions on the KV.

2024-11-08 21:07 UTC, mluker commented on src/az-containerapps-apim-appgw/deploy/terraform/app/main.tf
> +  subscription_id = "<subscription id>"
Comments apply to all of the .tf files:
- All of the values set to "<...>" should come in via variables (tvars and/or defaults) so this file does not have to be altered by the person running it.
- Resource should use random generated names, were applicable, so there are no name collisions with global resources. [This one works](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/pet) nicely.

2024-11-13 14:10 UTC, aminespinoza10 commented
Comments in first box have been resolved. 
* Migration from .NET Core 31 to .NET 8.0
* .devcontainer file updated

2024-11-13 14:12 UTC, aminespinoza10 commented on src/az-containerapps-apim-appgw/README.md
> +bash bicep-deploy.sh
Nice comments! All of them have been solved in the last push.

2024-11-15 19:33 UTC, aminespinoza10 commented on src/az-containerapps-apim-appgw/deploy/bash/bicep-deploy.sh
> +az keyvault certificate import --vault-name test-internal-001-kv --name root-cert --file root-cert.pfx --password "s5p2rm1n"
This has been modified and solved.

2024-12-11 14:02 UTC, mluker commented
@aminespinoza10 Performing PR maintenance and checking on the status of the PR review updates/comments.

2025-01-07 04:39 UTC, aminespinoza10 commented
PR has been updated focused in the Bicep bash deployment, I'll start working in Terraform script, just to save some time.

2025-02-22 22:03 UTC, mluker commented
Closing for now until there is more bandwidth for the author to collaborate.

2025-02-22 22:03 UTC, closed without merging